---
  context:
    question:
      headline: "Frage mit Antwortmöglichkeiten"
      text: "Fragetext der Frage 1"
    
    image:
      id: "asset-bild-fuer-bildbox-100"
      itemid: "bild-fuer-bildbox-100"
      class: "asset rs_skip_always figure-left"
      aspectratio: "1x1"
      src: "https://i.picsum.photos/id/1011/1420/800.jpg"
      alttext: "Bild mit gesperrter Version 1x1 XL - bitte nicht ändern (Foto: ard-foto s2-intern/extern, swr)"
      width: "1440"
      height: "1440"

      figcaption:
        caption: "Bildunterschrift"
        copyrightholder:
          - item: "ard-foto s2-intern/extern"
          - item: "swr"