---
  context:
    answers:
      - class: "answer-checked"
        label: "Antwort 1"
        voting: "57"
      - label: "Antwort 2"
        voting: "24"
      - label: "Antwort 3"
        voting: "19"