---
  context:
    radios:
      - id: "formField_antwort31"
        name: "formField_antworten"
        value: "antwort31"
        text: "Antwort 1"
      - id: "formField_antwort32"
        name: "formField_antworten"
        value: "antwort32"
        text: "Antwort 2"
      - id: "formField_antwort33"
        name: "formField_antworten"
        value: "antwort33"
        text: "Antwort 3"
      - id: "formField_antwort34"
        name: "formField_antworten"
        value: "antwort34"
        text: "Antwort 4"