---
  hidden: true
  context:
    image:
      w200-1: "http://unsplash.it/200/60"
      w200-2: "http://unsplash.it/200/100"
      w120-1: "http://unsplash.it/120/80"
      w130-1: "http://unsplash.it/130/60"

    placeholder: "Das ist ein Platzhalter"
    headline:
      h2: "Das ist eine tolle Headline"
      h3: "Noch eine Headline aus der Tiefe"
      subheading: "Subheadline"

    text: 
      lorem: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
      incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
      exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
      deutsch1: "Auch gibt es niemanden, der den Schmerz an sich liebt, sucht oder wünscht, nur, weil er Schmerz ist, es sei denn, es kommt zu zufälligen Umständen, in denen Mühen und Schmerz ihm große Freude bereiten können."
      deutsch2: "Um ein triviales Beispiel zu nehmen, wer von uns unterzieht sich je anstrengender körperlicher Betätigung, außer um Vorteile daraus zu ziehen?"
      deutsch3: "Aber wer hat irgend ein Recht, einen Menschen zu tadeln, der die Entscheidung trifft, eine Freude zu genießen, die keine unangenehmen Folgen hat, oder einen, der Schmerz vermeidet, welcher keine daraus resultierende Freude nach sich zieht?"
      deutsch4: "Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext."
      deutsch5: "Genau zu diesem Zwecke erschaffen, immer im Schatten meines großen Bruders »Lorem Ipsum«, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen. Denn esse est percipi - Sein ist wahrgenommen werden."

    url: "#"
    cta: "Call To Action"

    table:
      thead:
        th:
        - title: Table Heading 1
        - title: Table Heading 2
        - title: Table Heading 3
        - title: Table Heading 4
      tbody:
        tr:
        - td:
          - text: row 1 cell 1
          - text: row 1 cell 2
          - text: row 1 cell 3
          - text: row 1 cell 4

    breadcrumbs:
      - url: "#"
        text: Link 1
      - url: "#"
        text: Link 2
      - url: "#"
        text: Link 3
    
    cite:
      leistungsschwein: 
        text: "Sagt die faule Sau zum Leistungsschwein, Du wirst vor mir ein Schnitzel sein."
        author: "Klaus Eckel"
      diplomatie:
        text: "Diplomatie ist die Kunst, mit hundert Worten zu verschweigen, was man mit einem einzigen Wort sagen könnte."
        author: "Saint-John Perse"
      pelzig:
        text: "Warum dieses Jahr aufhängen, wenn es nächstes Jahr noch  bessere Gründe gibt?"
        author: "Erwin Pelzig"
      goethe:
        text: "Gerne der Zeiten gedenk ich, da alle Glieder gelenkig - bis auf eins. Doch die Zeiten sind vorüber, steif geworden alle Glieder - bis auf eins."
        author: "Johann Wolfgang von Goethe"
      hirschhausen:
        text: "Shit happens. Mal bist Du die Taube, mal das Denkmal."
        author: "Eckhard v. Hirschhausen"



