---
  hidden: true
  context:
    additionalText-left: "Weiterer Text mit Infos zur Antwort? Der Text kann auch ruhig etwas länger sein und über mehrere Zeilen gehen! (Dieser Text sollte rechts neben dem Bild stehen.)"
    additionalText-center: "Weiterer Text mit Infos zur Antwort? Es geht leider nur ein (!) weiterer Absatz. Dieser Text sollte über dem Bild stehen"
    additionalText-simple: "Weiterer Text mit Infos zur Antwort? Der Text kann auch ruhig etwas länger sein. Jeder aber nur einen (!) Absatz!"

    image-links-1:
      id: "asset-100"
      itemid: "id100"
      class: "asset rs_skip_always figure-left"
      aspectratio: "1x1"
      src: "https://trendblog.euronics.de/wp-content/uploads/2017/01/Seitenverhaeltnis_16_9.jpg"
      link: "#"
      height: "1440"
      width: "1440"
      alttext: "Bild mit gesperrter Version 1x1 XL - bitte nicht ändern (Foto: ard-foto s2-intern/extern, swr)"

      figcaption:
        caption: "linksbündig"
        copyrightholder:
          - item: "ard-foto s2-intern/extern"
          - item: "swr"

    image-center-1:
      id: "asset-200"
      itemid: "id200"
      class: "asset rs_skip_always figure-center"
      aspectratio: "1x1"
      src: "https://trendblog.euronics.de/wp-content/uploads/2017/01/Seitenverhaeltnis_16_9.jpg"
      link: "#"
      height: "1440"
      width: "1440"
      alttext: "Bild mit gesperrter Version 1x1 XL - bitte nicht ändern (Foto: ard-foto s2-intern/extern, swr)"

      figcaption:
        caption: "mittig"
        copyrightholder:
          - item: "ard-foto s2-intern/extern"
          - item: "swr"

    image-right-1:
      id: "asset-200"
      itemid: "id200"
      class: "asset rs_skip_always figure-right"
      aspectratio: "1x1"
      src: "https://trendblog.euronics.de/wp-content/uploads/2017/01/Seitenverhaeltnis_16_9.jpg"
      link: "#"
      height: "1440"
      width: "1440"
      alttext: "Bild mit gesperrter Version 1x1 XL - bitte nicht ändern (Foto: ard-foto s2-intern/extern, swr)"

      figcaption:
        caption: "rechtsbündig"
        copyrightholder:
          - item: "ard-foto s2-intern/extern"
          - item: "swr"

    detail-links:
      additionalText: "Weiterer Text mit Infos zur Antwort? Der Text kann auch ruhig etwas länger sein und über mehrere Zeilen gehen! (Dieser Text sollte rechts neben dem Bild stehen.)"
      image:
        id: "asset-600"
        itemid: "id600"
        class: "asset rs_skip_always figure-left"
        aspectratio: "1x1"
        src: "https://trendblog.euronics.de/wp-content/uploads/2017/01/Seitenverhaeltnis_16_9.jpg"
        link: "#"
        height: "1440"
        width: "1440"
        alttext: "Bild mit gesperrter Version 1x1 XL - bitte nicht ändern (Foto: ard-foto s2-intern/extern, swr)"
      figcaption:
        caption: "linksbündig"
        copyrightholder:
          - item: "ard-foto s2-intern/extern"
          - item: "swr"

    detail-rechts:
      additionalText: "Weiterer Text mit Infos zur Antwort? Der Text kann auch ruhig etwas länger sein. Jeder aber nur einen (!) Absatz!"
      image:
        id: "asset-700"
        itemid: "id700"
        class: "asset rs_skip_always figure-right"
        aspectratio: "1x1"
        src: "https://trendblog.euronics.de/wp-content/uploads/2017/01/Seitenverhaeltnis_16_9.jpg"
        link: "#"
        height: "1440"
        width: "1440"
        alttext: "Bild mit gesperrter Version 1x1 XL - bitte nicht ändern (Foto: ard-foto s2-intern/extern, swr)"

      figcaption:
        caption: "rechtsbündig"
        copyrightholder:
          - item: "ard-foto s2-intern/extern"
          - item: "swr"
